var cProgramming = [
  'Arrays',
  'Bitwise Operators',
  'Command Line Arguments',
  'Complicated Declarations',
  'Const',
  'Control Instructions',
  'C Preprocessor',
  'Declarations and Initializations',
  'Expressions',
  'Floating Point Issues',
  'Functions',
  'Input Output',
  'Library Functions',
  'Memory Allocation',
  'Pointers',
  'Strings',
  'Structures Unions Enums',
  'Typedef',
  'Variable Number of Arguments'
];

var generalScience = [
  "Elements and Metals",
  "Measurements",
  "Nuclear Science",
  "Synthetic Materials",
];

var basicElectronics = [
  'Alternating Current and Voltage',
  'Alternating Current vs\n Direct Current',
  'Analog and Digital Converters',
  'Analog to Digital',
  'Arithmetic Operations and Circuits',
  'Basic Op-Amp Circuits',
  'Bipolar Junction Transistors',
  'Capacitors',
  'Combinational Logic Circuits',
  'Computer Hardware and Software',
  'Diodes and Applications',
  'Field Effect Transistors (FET)',
  'Flip-Flops and Timers',
  'Inductors',
  'Logic Circuit Simplification',
  'Logic Gates',
  'Magnetism and Electromagnetism',
  'Measurement Conversion and Control',
  'Number Systems and Codes',
  "Ohm's Law",
  'Operational Amplifiers',
  'Parallel Circuits',
  'Programmable Logic Devices (PLD)',
  'Quantities and Units',
  'RC Circuits',
  'RL Circuits',
  'RLC Circuits and Resonance',
  'Resistance and Power',
  'Semiconductor Memory',
  'Semiconductor Principles',
  'Sequential Logic Circuits',
  'Series Circuits',
  'Series-Parallel Circuits',
  'Special-Purpose Op-Amp Circuits',
  'Standard Logic Devices (SLD)',
  'Testing and Troubleshooting',
  'Thyristors and Tranducers',
  'Time Response of Reactive Circuits',
  'Transformers',
  'Transistors and Applications',
  'Voltage and Current'
];

var cppProgramming = [
  'Constructors and Destructors',
  'Exception Handling',
  'File Handling',
  'Friend Functions',
  'Function Overloading',
  'Functions',
  'Inheritance',
  'Memory Management',
  'OOPS Concepts',
  'Objects and Classes',
  'Operator Overloading',
  'References',
  'Templates'
];

var computerScience = [
  'Artificial Intelligence',
  'Automation System',
  'Computer Fundamentals I',
  'Computer Fundamentals II',
  'Computer Fundamentals III',
  'Computer Fundamentals IV',
  'Computer Hardware I',
  'Computer Hardware II',
//  'Database Systems',
//  'Digital Computer Electronics',
//  'Disk Operating System (DOS)',
//  'Electronic Principles',
//  'Language Processors',
//  'Linux',
//  'Management Information Systems',
//  'Networking',
//  'Object Oriented Programming\n Using C++',
//  'Operating Systems Concepts',
//  'System Analysis and Design',
//  'Unix',
//  'Windows 2000 Server',
//  'Windows NT',
];

var database = [
  'Advanced SQL',
  'Data Modeling with ER Model',
  'Data Models into Database Designs',
  'Data Warehousing',
  'Data and Database Administration',
  'Database Design Using Normalization',
  'Database Processing for BIS',
  'Database Redesign',
  'Distributed Databases',
  'ER Model and Business Rules',
  'Introduction to Database',
  'Introduction to SQL',
  'JDBC Java Server Pages and MySQL',
  'Logical Database Design',
  'Managing Databases with Oracle',
  'Managing Multiuser Databases',
  'Modeling Data in the Organization',
  'ODBC OLE DB ADO and ASP',
  'Object-Oriented Data Modeling',
  'Object-Oriented Database',
  'Physical Database Design',
  'SQL Server 2000',
  'SQL for Database Construction',
  'The Client-Server Database',
  'The Database Development Process',
  'The Database Environment',
  'The Internet Database Environment',
  'The Relational Model and\n Normalization',
  'XML and ADO.NET'
];

var digitalElectronics = [
//  'Boolean Algebra and Logic\n Simplification',
//  'Code Converters and Multiplexers',
//  'Combinational Logic Analysis',
  'Combinational Logic Circuits',
//  'Computers',
//  'Counters',
//  'Describing Logic Circuits',
//  'Digital Arithmetic Operations and\n Circuits',
//  'Digital Concepts',
//  'Digital Design',
//  'Digital Signal Processing',
//  'Digital System Projects Using HDL',
//  'Ex-OR and Ex-NOR Gates',
//  'Flip-Flops',
//  'Integrated Circuit Technologies',
//  'Integrated-Circuit Logic Families',
//  'Interfacing to the Analog World',
//  'Logic Families and Their\n Characteristics',
  'Logic Gates',
//  'MSI Logic Circuits',
//  'Memory and Storage',
//  'Microprocessor Fundamentals',
//  'Multivibrators and 555 Timer',
  'Number Systems and Codes',
//  'Programmable Logic Device',
//  'Shift Registers',
//  'Signals and Switches',
//  'The 8051 Microcontroller',
];

var electrical = [
//  '3-Phase Systems in Power\n Applications',
  'Alternating Current and Voltage',
//  'Branch Loop and Node Analyses',
  'Capacitors',
//  'Circuit Theorems and Conversions',
//  'Circuit Theorems in AC Analysis',
//  'Energy and Power',
  'Inductors',
  'Magnetism and Electromagnetism',
//  'Ohms Law',
  'Parallel Circuits',
//  'Passive Filters',
  'Quantities and Units',
  'RC Circuits',
  'RL Circuits',
  'RLC Circuits and Resonance',
  'Series Circuits',
  'Series-Parallel Circuits',
  'Time Response of Reactive Circuits',
  'Transformers',
//  'Voltage Current and Resistance',
];

var electronicsAndCommunication = [
//  'Analog Electronics',
//  'Automatic Control Systems',
//  'Communication Systems',
//  'Digital Electronics',
//  'Electromagnetic Field Theory',
//  'Electronic Devices and Circuits',
//  'Materials and Components',
//  'Measurements and Instrumentation',
//  'Microprocessors',
//  'Microwave Communication',
//  'Networks Analysis and Synthesis',
//  'Power Electronics',
//  'Radio Receivers',
//  'Satellite Communication',
//  'Signals and Systems',
];

var electronicsDeviceAndCircuitTheory = [
//  'Active Filters',
//  'Amplifier Frequency Response',
//  'BJT Amplifiers',
//  'BJT Devices',
//  'BJT and FET Frequency Response',
  'Basic Op-Amp Circuits',
  'Bipolar Junction Transistors',
//  'Communications',
//  'DC Biasing-BJTs',
//  'DC Biasing-FETs',
//  'Diode Applications',
//  'FET Amplifiers',
//  'FET Devices',
//  'Field-Effect Transistors',
//  'Linear-Digital ICs',
//  'Op-Amp Applications',
  'Operational Amplifiers',
//  'Oscillator Circuits',
//  'PNPN',
//  'Power Amplifiers',
//  'Semiconductor Diodes',
//  'Semiconductors',
//  'Special-Purpose Diodes',
  'Special-Purpose Op-Amp Circuits',
//  'Thyristors',
//  'Transistor Bias Circuits',
//  'Two-Terminal Devices',
//  'Voltage Regulators',
];

var java = [
  'Assertions',
  'Declarations and Access Control',
  'Exceptions',
  'Flow Control',
  'Garbage Collections',
  'Inner Classes',
  'Java.lang Class',
  'Language Fundamentals',
  'Objects and Collections',
  'Operators and Assignments',
  'Threads',
];

var networking = [
  'EIGRP and OSPF',
  'IOS and Security Device Manager',
  'IP Routing',
  'IPv6',
  'Internetworking',
  'Managing a Cisco Internetwork',
  'Network Address Translation',
  'Networking Basics',
  'Security',
  'Spanning Tree Protocol',
  'Subnetting',
  'TCP/IP',
  'Virtual LANs',
  'Wide Area Networks',
  'Wireless Technologies',
];
